apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-doom
  labels:
    app: {{ .Release.Name }}-doom
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-doom
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-doom
    spec:
      containers:
        - name: doom
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
